variables:
  PROJECT_NAME: game_pc
  DEPLOY_DEV_PATH: /home/wwwroot/
  DEPLOY_MASTER_PATH: /www/wwwroot/

stages:
  - deploy

deploy_dev:
  stage: deploy
  script:
    - rsync -avzu --progress --delete -e ssh --exclude='.git' $CI_PROJECT_DIR www@192.168.1.242:$DEPLOY_DEV_PATH
    
  only:
    - dev
deploy_master:
  stage: deploy
  script:
    - rsync -avzu --progress --delete -e 'ssh -p 3287' --exclude='.git'  $CI_PROJECT_DIR www@119.8.38.253:$DEPLOY_MASTER_PATH
  only:
    - master
deploy_xjp:
  stage: deploy
  script:
    - rsync -avzu --progress --delete -e 'ssh -p 3287' --exclude='.git'  $CI_PROJECT_DIR www@103.103.69.61:$DEPLOY_MASTER_PATH
  only:
    - xjp
